services:
  druid:
    image: apache/druid:36.0.0
    env_file:
      - ./druid/environment
    ports:
      - "8888:8888"
      - "8082:8082"
    volumes:
      - druid_data:/opt/druid/var
      - ./druid:/opt/metricforge/docker-druid:ro
      - ../druid/ingestion_specs:/opt/metricforge/druid/ingestion_specs:ro
      - ../druid/sample_queries:/opt/metricforge/druid/sample_queries:ro
    entrypoint:
      - /bin/bash
      - /opt/metricforge/docker-druid/run-single-server.sh
    networks:
      - metricforge_net
