druid.extensions.loadList=["druid-kafka-indexing-service","druid-s3-extensions"]
druid.zk.service.host=localhost
druid.metadata.storage.type=derby
druid.storage.type=local
druid.indexer.logs.type=file
druid.processing.tmpDir=/opt/druid/var/tmp
